algorithm: 
  name: aco
  time-step: 0.05

algorithm-parameters:

  boids: # Boids parameters, used only if "algorithm name: boids"
    weights:
      seek: 1.0
      avoid: 3.5
      separation: 2.0
      alignment: 0.5
      cohesion: 0.5
    agents:
      size: 5.0             # is this for plotting?
      max-speed: 2.5
      max-force: 0.3
      vision-radius: 7.0
      min-separation: 15.0  # 3 * agent_size # what is this?
      wall-avoid-distance: 10.0

world:
  name: test_environment
  dimensions: [100, 100]
  num-agents: 100
  exits:
    - [[100, 40], [100, 60]]
  walls:
    - [[50, 0], [50, 70]]
  add_external_walls: true

visualization:
  activate: true
  dimensions: [1200, 800]
  window-name: "Crowd Simulation"

  padding: 10
  right-border: 50
  left-border: 50
  top-border: 80
  bottom-border: 120
   
  background-color: [0, 0, 0]
  agent-color: [0, 102, 255]
  wall-color: [200, 200, 200]
  exit-color: [57, 255, 20]
  title-color: [255, 0, 0]
  text-color: [255, 255, 255]

