algorithm: 
  name: aco #[options: boids, pso-local, aco]
  time-step: 0.01
  seed: 5

algorithm-parameters:

  boids: # Boids parameters, used only if "algorithm name: boids"
    weights:
      seek: 2.0
      avoid: 3.5
      separation: 2.0
      alignment: 0.5
      cohesion: 0.5
    agents:
      size: 5.0             # is this for plotting?
      max-speed: 4.0
      max-force: 0.3
      vision-radius: 7.0   # 80.0
      min-separation: 15.0  # 3 * agent_size # what is this?
      wall-avoid-distance: 10.0

  pso-local:  # PSO parameters
    neighborhood_radius: 5.0
    inertia_weight: 0.5
    cognitive_weight: 1.5
    social_weight: 1.5

  aco:
    num-ants-in-simulation: 250
    num-iterations: 1
    alpha: 1.0
    beta: 2.0
    evaporation-rate: 0.2

    # Graph parameters
    graph-type: grid   # options: ["grid", "PRM"]
    n: 20             # number of rows if "graph-type"="grid", number of nodes if "graph-type"="PRM"
    m: 10             # used only if graph-type is "grid", number of columns
    k-connectivity: 2 # k-connectivity. If "graph-type"="grid" only options are "1"->4-connectivity, "2"->8-connectivity

# TODO : get agents parameter shared among algorihtms here

world:
  type: two_doors          # options: ["bottleneck", "two_doors", "slalom", "empty", "custom"]
  name: test_environment

  # following parameters are considered only if "type: custom"
  dimensions: [10,10]
  num-agents: 90
  # spawn: random       # options: ["random", "densed"]
  exits:
    - [[10, 4], [10, 6]]
  walls:
    #- [[5, 0], [5, 7]]

visualization:
  activate: false
  dimensions: [1200, 800]
  window-name: "Crowd Simulation"

  padding: 50
  right-border: 300
  left-border: 300
  top-border: 0
  bottom-border: 120
   
  background-color: [0, 0, 0]
  agent-color: [243, 255, 20]
  wall-color: [200, 200, 200]
  exit-color: [57, 255, 20]
  title-color: [255, 0, 0]
  text-color: [255, 255, 255]

