algorithm: 
  name: boids-without-panic #[options: boids-without-panic, boids-with-panic, pso-local]
  time-step: 0.005
  seed: 2

algorithm-parameters:

  boids: # Boids parameters, used only if "algorithm name: boids"
    weights:
      seek: 2.0
      avoid: 3.5
      separation: 2.0
      alignment: 0.5
      cohesion: 0.5
    agents:
      size: 5.0             # is this for plotting?
      max-speed: 4.0
      max-force: 0.3
      vision-radius: 7.0   # 80.0
      min-separation: 15.0  # 3 * agent_size # what is this?
      wall-avoid-distance: 10.0

  pso-local:  # PSO parameters
    neighborhood_radius: 5.0
    inertia_weight: 0.5
    cognitive_weight: 1.5
    social_weight: 1.5

  aco:


world:
  type: custom          # options: ["bottleneck", "two_doors", "slalom", "empty", "custom"]
  name: test_environment
  dimensions: [100,100]
  num-agents: 100
  exits:
    - [[100, 40], [100, 60]]
  walls:
    - [[50, 0], [50, 70]]

visualization:
  activate: true
  dimensions: [1200, 800]
  window-name: "Crowd Simulation"

  padding: 10
  right-border: 300
  left-border: 300
  top-border: 0
  bottom-border: 120
   
  background-color: [0, 0, 0]
  agent-color: [243, 255, 20]
  wall-color: [200, 200, 200]
  exit-color: [57, 255, 20]
  title-color: [255, 0, 0]
  text-color: [255, 255, 255]

