algorithm: 
  name: boids           # [options: boids, pso, aco]
  time-step: 0.01
  seed: 1

algorithm-parameters:

  boids:              # used only if "algorithm-name: boids"
    weights:
      seek: 8.6707
      avoid: 2.8789
      separation: 2.5753
      alignment: 0.1000
      cohesion: 0.1000
    agents:
      max-speed: 1.0
      max-force: 0.1
      vision-radius: 80.0   
      min-separation: 25

  pso:                # used only if "algorithm-name: pso"
    neighborhood_radius: 10.0
    inertia_weight: 0.4
    cognitive_weight: 1.0
    social_weight: 1.5

  aco:                # used only if "algorithm-name: aco"  
    num-ants-in-simulation: 105
    num-iterations: 300
    alpha: 1
    beta: 2
    evaporation-rate: 0.3

    # Graph parameters
    graph-type: grid   # options: ["grid", "PRM"]
    n: 10              # number of rows if "graph-type"="grid", number of nodes if "graph-type"="PRM"
    m: 10              # used only if graph-type is "grid", number of columns
    k-connectivity: 2  # k-connectivity. If "graph-type"="grid" only options are "1"->4-connectivity, "2"->8-connectivity

# TODO : get agents parameter shared among algorihtms here

world:
  type: two_doors          # options: ["bottleneck", "two_doors", "slalom", "empty", "custom"]
  name: test_environment

  # the following parameters are considered only if "type: custom"
  dimensions: [10,10]
  num-agents: 20
  # spawn: random       # options: ["random", "densed"]
  exits:
    - [[10, 4], [10, 6]]
  walls:
    #- [[5, 0], [5, 7]]

visualization:
  activate: true
  window-name: "Crowd Simulation"
   
  background-color: [0, 0, 0]
  agent-color: [243, 255, 20]
  wall-color: [200, 200, 200]
  exit-color: [57, 255, 20]
  title-color: [255, 0, 0]
  text-color: [255, 255, 255]

